# Lang
language: zh-CN

# Mode:dark,three
mode: three

# Header
menu:
  Home: /
  Archives: /archives
  Categories: header_categories
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: zly
description: 技不如人，甘拜下风
links:
  Blog: /archives
  GitHub: https://github.com/Lyz1052


# Info
footer_content: 
  - "有时候输了比赛，总感觉队友不给力. *—— 徐志雷*"
  - "做人最重要的是开心. *—— 朱东勇*"
  - "The quick you let go of old cheese, the sooner you find new cheese. *—— Mice Haw*"

# THREEJS
effect: 
  home: true
  orbit_control: true
  bird: true
  sky: true

  archive: true
  maxtag: 3
  tweenable: true
  default: "table"